version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"

  # adminer:
  #   image: adminer
  #   environment:
  #     ADMINER_DEFAULT_SERVER: postgres
  #   ports:
  #     - 8091:8080

  # mailhog:
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'
  #   ports:
  #     - 1025:1025 # smtp server
  #     - 8025:8025 # web ui

  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio_storage:/data
  #   environment:
  #     MINIO_ROOT_USER: masoud
  #     MINIO_ROOT_PASSWORD: Strong#Pass#2022
  #   command: server --console-address ":9001" /data

volumes:
  # minio_storage: {}
  db_data:
  redis_data:
    driver: local
